name: Producer CPP JNI Builds

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  mac-os:
    strategy:
      matrix:
        dependencies:
          - ON
          - OFF
        mac:
          - name: Intel x86_64
            runner: macos-13
          - name: Apple Silicon
            runner: macos-15

      fail-fast: false

    name: JNI ${{ matrix.mac.name }} deps=${{ matrix.dependencies }}

    runs-on: ${{ matrix.mac.runner }}
    steps:
      - name: Setup XCode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        if: ${{ matrix.dependencies == 'OFF' }}
        run: |
          brew install log4cplus

      - name: Build JNI (CMake)
        run: |
          mkdir build && cd build
          
          if [[ "${{ matrix.dependencies }}" == "ON" ]]; then
            cmake .. -DBUILD_JNI=ON -DBUILD_DEPENDENCIES=ON -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -BUILD_COMMON_CURL=OFF
          else
            export OPENSSL_ROOT_DIR=$(brew --prefix openssl)
            export OPENSSL_LIBRARIES=$(brew --prefix openssl)/lib
            export OPENSSL_INCLUDE_DIR=$(brew --prefix openssl)/include
            cmake .. -DBUILD_JNI=ON -DBUILD_DEPENDENCIES=OFF
          fi

      - name: Build JNI (make)
        working-directory: ./build
        run: |
          make -j$(sysctl -n hw.cpu)