name: Producer CPP JNI Builds

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  mac-os:
    strategy:
      matrix:
        config:
          - name: Intel x86_64
            runner: macos-13
          - name: Apple Silicon
            runner: macos-15
          - name: Ubuntu 22.04
            runner: ubuntu-latest
            container: public.ecr.aws/ubuntu/ubuntu:22.04_stable
          - name: Ubuntu 20.04
            runner: ubuntu-latest
            container: public.ecr.aws/ubuntu/ubuntu:20.04_stable

      fail-fast: false

    name: JNI ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.runner }}
    container: ${{ matrix.config.container || '' }}

    env:
      DEBIAN_FRONTEND: noninteractive
      JAVA_VERSIONS: "11 17 21"

    steps:
      - name: Setup XCode
        if: ${{ runner.os == 'macOS' }}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install Dependencies (Linux only)
        if: runner.os == 'Linux'
        run: |
          apt update
          apt install -y git cmake build-essential

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Build JNI with Multiple Java Versions
        run: |
          for java_version in $JAVA_VERSIONS; do
            echo "Setting up Java JDK $java_version"
            echo "::group::Setting up Java JDK $java_version"
            echo "----------------------------------------"
            rm -rf /opt/java
            mkdir -p /opt/java
            ln -sfn $(actions/setup-java@v4 --distribution 'corretto' --java-version "$java_version") /opt/java/current
            export JAVA_HOME=/opt/java/current
            java -version
            javac -version
            echo "::endgroup::"

            echo "Building JNI with Java $java_version"
            echo "::group::Building JNI with Java $java_version"

            # Note: Dependencies on/off shouldn't make any difference since
            # the only dependency for the JNI is PIC

            mkdir -p build && cd build
            cmake .. -DBUILD_JNI_ONLY=ON
            make -j
            cd ..
            rm -rf build
            echo "::endgroup::"
          done
